### ISSUE TITLE
cgroup memory not mounted error

### ISSUE THREAD

**Issue by scirelli** [abelperezok/kubernetes-raspberry-pi-cluster-hat#1]
I ran into a cgroups issue when following this 

> Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]

Follow this [guide](https://downey.io/blog/exploring-cgroups-raspberry-pi/) to enabling cgroup memory on the Pi Zero

The steps were to add `cgroup_enable=memory cgroup_memory=1` to the list of params in `/boot/cmdline.txt`

**Comment by abelperezok** [comment]
Hi @scirelli I'm not sure what is the purpose of this issue you just opened, if you found something inaccurate or incomplete in the guide, please submit a pull request with the amends, I'll be happy to review it.

**Comment by scirelli** [comment]
Sorry, sure.
